# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1088, 553)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setBaseSize(QtCore.QSize(0, 0))
        self.splitter.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setChildrenCollapsible(True)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.trainingLabelsButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trainingLabelsButton.sizePolicy().hasHeightForWidth())
        self.trainingLabelsButton.setSizePolicy(sizePolicy)
        self.trainingLabelsButton.setObjectName("trainingLabelsButton")
        self.gridLayout_2.addWidget(self.trainingLabelsButton, 2, 2, 1, 1)
        self.trainingLabelsPath = QtWidgets.QLabel(self.groupBox)
        self.trainingLabelsPath.setObjectName("trainingLabelsPath")
        self.gridLayout_2.addWidget(self.trainingLabelsPath, 2, 1, 1, 1)
        self.validationLabelPath = QtWidgets.QLabel(self.groupBox)
        self.validationLabelPath.setObjectName("validationLabelPath")
        self.gridLayout_2.addWidget(self.validationLabelPath, 4, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 3, 0, 1, 1)
        self.trainingImageButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trainingImageButton.sizePolicy().hasHeightForWidth())
        self.trainingImageButton.setSizePolicy(sizePolicy)
        self.trainingImageButton.setObjectName("trainingImageButton")
        self.gridLayout_2.addWidget(self.trainingImageButton, 1, 2, 1, 1)
        self.trainingImagePath = QtWidgets.QLabel(self.groupBox)
        self.trainingImagePath.setObjectName("trainingImagePath")
        self.gridLayout_2.addWidget(self.trainingImagePath, 1, 1, 1, 1)
        self.validationImagePath = QtWidgets.QLabel(self.groupBox)
        self.validationImagePath.setObjectName("validationImagePath")
        self.gridLayout_2.addWidget(self.validationImagePath, 3, 1, 1, 1)
        self.validationImageButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.validationImageButton.sizePolicy().hasHeightForWidth())
        self.validationImageButton.setSizePolicy(sizePolicy)
        self.validationImageButton.setObjectName("validationImageButton")
        self.gridLayout_2.addWidget(self.validationImageButton, 3, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 4, 0, 1, 1)
        self.validationLabelButton = QtWidgets.QPushButton(self.groupBox)
        self.validationLabelButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.validationLabelButton.sizePolicy().hasHeightForWidth())
        self.validationLabelButton.setSizePolicy(sizePolicy)
        self.validationLabelButton.setSizeIncrement(QtCore.QSize(0, 0))
        self.validationLabelButton.setBaseSize(QtCore.QSize(0, 0))
        self.validationLabelButton.setIconSize(QtCore.QSize(16, 16))
        self.validationLabelButton.setObjectName("validationLabelButton")
        self.gridLayout_2.addWidget(self.validationLabelButton, 4, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 2, 0, 1, 1)
        self.loadFilesButton = QtWidgets.QPushButton(self.groupBox)
        self.loadFilesButton.setObjectName("loadFilesButton")
        self.gridLayout_2.addWidget(self.loadFilesButton, 5, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.validationExampleNum = QtWidgets.QLineEdit(self.groupBox_3)
        self.validationExampleNum.setEnabled(False)
        self.validationExampleNum.setObjectName("validationExampleNum")
        self.gridLayout.addWidget(self.validationExampleNum, 1, 1, 1, 1)
        self.trainingExampleNum = QtWidgets.QLineEdit(self.groupBox_3)
        self.trainingExampleNum.setEnabled(False)
        self.trainingExampleNum.setObjectName("trainingExampleNum")
        self.gridLayout.addWidget(self.trainingExampleNum, 0, 1, 1, 1)
        self.maxTraining = QtWidgets.QLabel(self.groupBox_3)
        self.maxTraining.setObjectName("maxTraining")
        self.gridLayout.addWidget(self.maxTraining, 0, 2, 1, 1)
        self.maxValidation = QtWidgets.QLabel(self.groupBox_3)
        self.maxValidation.setObjectName("maxValidation")
        self.gridLayout.addWidget(self.maxValidation, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 3, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 4, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 2, 0, 1, 1)
        self.epochNumber = QtWidgets.QLineEdit(self.groupBox_2)
        self.epochNumber.setObjectName("epochNumber")
        self.gridLayout_3.addWidget(self.epochNumber, 3, 1, 1, 1)
        self.momentumSlider = QtWidgets.QSlider(self.groupBox_2)
        self.momentumSlider.setMaximum(100)
        self.momentumSlider.setOrientation(QtCore.Qt.Horizontal)
        self.momentumSlider.setObjectName("momentumSlider")
        self.gridLayout_3.addWidget(self.momentumSlider, 2, 1, 1, 1)
        self.l2Slider = QtWidgets.QSlider(self.groupBox_2)
        self.l2Slider.setMaximum(100)
        self.l2Slider.setOrientation(QtCore.Qt.Horizontal)
        self.l2Slider.setObjectName("l2Slider")
        self.gridLayout_3.addWidget(self.l2Slider, 1, 1, 1, 1)
        self.momentum = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.momentum.setMaximum(1.0)
        self.momentum.setSingleStep(0.01)
        self.momentum.setObjectName("momentum")
        self.gridLayout_3.addWidget(self.momentum, 2, 3, 1, 1)
        self.l2 = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.l2.setMaximum(1.0)
        self.l2.setSingleStep(0.01)
        self.l2.setObjectName("l2")
        self.gridLayout_3.addWidget(self.l2, 1, 3, 1, 1)
        self.stepSizeSlider = QtWidgets.QSlider(self.groupBox_2)
        self.stepSizeSlider.setMaximum(100)
        self.stepSizeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.stepSizeSlider.setObjectName("stepSizeSlider")
        self.gridLayout_3.addWidget(self.stepSizeSlider, 0, 1, 1, 1)
        self.stepSize = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.stepSize.setMaximum(1.0)
        self.stepSize.setSingleStep(0.01)
        self.stepSize.setObjectName("stepSize")
        self.gridLayout_3.addWidget(self.stepSize, 0, 3, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.scrollArea = QtWidgets.QScrollArea(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setSizeIncrement(QtCore.QSize(0, 0))
        self.scrollArea.setBaseSize(QtCore.QSize(0, 0))
        self.scrollArea.setLineWidth(1)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 260, 454))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.testowy_label1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.testowy_label1.setObjectName("testowy_label1")
        self.verticalLayout_3.addWidget(self.testowy_label1)
        self.testowy_label2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.testowy_label2.setObjectName("testowy_label2")
        self.verticalLayout_3.addWidget(self.testowy_label2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.splitter)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startButton.sizePolicy().hasHeightForWidth())
        self.startButton.setSizePolicy(sizePolicy)
        self.startButton.setMinimumSize(QtCore.QSize(120, 30))
        self.startButton.setBaseSize(QtCore.QSize(13, 14))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.startButton.setFont(font)
        self.startButton.setObjectName("startButton")
        self.horizontalLayout.addWidget(self.startButton)
        self.closeButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closeButton.sizePolicy().hasHeightForWidth())
        self.closeButton.setSizePolicy(sizePolicy)
        self.closeButton.setMinimumSize(QtCore.QSize(120, 30))
        self.closeButton.setBaseSize(QtCore.QSize(13, 14))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.closeButton.setFont(font)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout.addWidget(self.closeButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1088, 21))
        self.menubar.setObjectName("menubar")
        self.menuDane = QtWidgets.QMenu(self.menubar)
        self.menuDane.setObjectName("menuDane")
        self.menuKonfiguracja = QtWidgets.QMenu(self.menuDane)
        self.menuKonfiguracja.setObjectName("menuKonfiguracja")
        self.menuProjekt = QtWidgets.QMenu(self.menubar)
        self.menuProjekt.setObjectName("menuProjekt")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionZapisz = QtWidgets.QAction(MainWindow)
        self.actionZapisz.setObjectName("actionZapisz")
        self.actionWczytaj = QtWidgets.QAction(MainWindow)
        self.actionWczytaj.setObjectName("actionWczytaj")
        self.actionO_projekcie = QtWidgets.QAction(MainWindow)
        self.actionO_projekcie.setObjectName("actionO_projekcie")
        self.menuKonfiguracja.addAction(self.actionZapisz)
        self.menuKonfiguracja.addAction(self.actionWczytaj)
        self.menuDane.addAction(self.menuKonfiguracja.menuAction())
        self.menuProjekt.addAction(self.actionO_projekcie)
        self.menubar.addAction(self.menuDane.menuAction())
        self.menubar.addAction(self.menuProjekt.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Linear Regression"))
        self.groupBox.setTitle(_translate("MainWindow", "Dane"))
        self.trainingLabelsButton.setText(_translate("MainWindow", "Wybierz"))
        self.trainingLabelsPath.setText(_translate("MainWindow", "Nie wybrano ścieżki"))
        self.validationLabelPath.setText(_translate("MainWindow", "Nie wybrano ścieżki"))
        self.label_2.setText(_translate("MainWindow", "Zbiór walidacyjny - obrazy"))
        self.trainingImageButton.setText(_translate("MainWindow", "Wybierz"))
        self.trainingImagePath.setText(_translate("MainWindow", "Nie wybrano ścieżki"))
        self.validationImagePath.setText(_translate("MainWindow", "Nie wybrano ścieżki"))
        self.validationImageButton.setText(_translate("MainWindow", "Wybierz"))
        self.label_12.setText(_translate("MainWindow", "Zbiór walidacyjny - etykiety"))
        self.validationLabelButton.setText(_translate("MainWindow", "Wybierz"))
        self.label.setText(_translate("MainWindow", "Zbiór treningowy - obrazy"))
        self.label_11.setText(_translate("MainWindow", "Zbiór treningowy - etykiety"))
        self.loadFilesButton.setText(_translate("MainWindow", "Wczytaj"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Przykłady"))
        self.label_3.setText(_translate("MainWindow", "Liczba przykładów treningwych"))
        self.label_4.setText(_translate("MainWindow", "Liczba przykładów walidacyhnych"))
        self.maxTraining.setText(_translate("MainWindow", "Max:0"))
        self.maxValidation.setText(_translate("MainWindow", "Max:0"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Hiperparametry"))
        self.label_7.setText(_translate("MainWindow", "Długość kroku"))
        self.label_9.setText(_translate("MainWindow", "Liczba epoch"))
        self.label_8.setText(_translate("MainWindow", "Współczynnik l2"))
        self.label_10.setText(_translate("MainWindow", "Momentum"))
        self.testowy_label1.setText(_translate("MainWindow", "aaaaaaaaaaaaaaaaaaaaa"))
        self.testowy_label2.setText(_translate("MainWindow", "bbbbbbbbbbbbbbb"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.closeButton.setText(_translate("MainWindow", "Zamknij"))
        self.menuDane.setTitle(_translate("MainWindow", "Dane"))
        self.menuKonfiguracja.setTitle(_translate("MainWindow", "Konfiguracja"))
        self.menuProjekt.setTitle(_translate("MainWindow", "Projekt"))
        self.actionZapisz.setText(_translate("MainWindow", "Zapisz"))
        self.actionZapisz.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionWczytaj.setText(_translate("MainWindow", "Wczytaj"))
        self.actionWczytaj.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionO_projekcie.setText(_translate("MainWindow", "O projekcie"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
