# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1050, 556)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setBaseSize(QtCore.QSize(0, 0))
        self.splitter.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setChildrenCollapsible(True)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.maxValidate = QtWidgets.QLabel(self.groupBox)
        self.maxValidate.setObjectName("maxValidate")
        self.gridLayout_2.addWidget(self.maxValidate, 6, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 6, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 5, 0, 1, 1)
        self.trainImages = QtWidgets.QLineEdit(self.groupBox)
        self.trainImages.setObjectName("trainImages")
        self.gridLayout_2.addWidget(self.trainImages, 1, 2, 1, 1)
        self.validateSize = QtWidgets.QLineEdit(self.groupBox)
        self.validateSize.setObjectName("validateSize")
        self.gridLayout_2.addWidget(self.validateSize, 6, 2, 1, 1)
        self.trainLabels = QtWidgets.QLineEdit(self.groupBox)
        self.trainLabels.setObjectName("trainLabels")
        self.gridLayout_2.addWidget(self.trainLabels, 2, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.validateImages = QtWidgets.QLineEdit(self.groupBox)
        self.validateImages.setObjectName("validateImages")
        self.gridLayout_2.addWidget(self.validateImages, 3, 2, 1, 1)
        self.maxTraining = QtWidgets.QLabel(self.groupBox)
        self.maxTraining.setObjectName("maxTraining")
        self.gridLayout_2.addWidget(self.maxTraining, 5, 3, 1, 1)
        self.validateLabels = QtWidgets.QLineEdit(self.groupBox)
        self.validateLabels.setObjectName("validateLabels")
        self.gridLayout_2.addWidget(self.validateLabels, 4, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 3, 0, 1, 1)
        self.trainSize = QtWidgets.QLineEdit(self.groupBox)
        self.trainSize.setObjectName("trainSize")
        self.gridLayout_2.addWidget(self.trainSize, 5, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 2, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 4, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.stepSize = QtWidgets.QLineEdit(self.groupBox_2)
        self.stepSize.setObjectName("stepSize")
        self.gridLayout_3.addWidget(self.stepSize, 0, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 3, 0, 1, 1)
        self.epochs = QtWidgets.QLineEdit(self.groupBox_2)
        self.epochs.setObjectName("epochs")
        self.gridLayout_3.addWidget(self.epochs, 3, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        self.momentum = QtWidgets.QLineEdit(self.groupBox_2)
        self.momentum.setObjectName("momentum")
        self.gridLayout_3.addWidget(self.momentum, 2, 2, 1, 1)
        self.l2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.l2.setObjectName("l2")
        self.gridLayout_3.addWidget(self.l2, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.scrollArea = QtWidgets.QScrollArea(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setSizeIncrement(QtCore.QSize(0, 0))
        self.scrollArea.setBaseSize(QtCore.QSize(0, 0))
        self.scrollArea.setLineWidth(1)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 144, 353))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        # important
        self.testowy_label3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.testowy_label3.setObjectName("testowy_label3")
        self.verticalLayout_3.addWidget(self.testowy_label3)
        # end
        #important
        self.testowy_label1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.testowy_label1.setObjectName("testowy_label1")
        self.verticalLayout_3.addWidget(self.testowy_label1)
        #end
        self.testowy_label2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.testowy_label2.setObjectName("testowy_label2")
        self.verticalLayout_3.addWidget(self.testowy_label2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.splitter)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startButton.sizePolicy().hasHeightForWidth())
        self.startButton.setSizePolicy(sizePolicy)
        self.startButton.setMinimumSize(QtCore.QSize(120, 30))
        self.startButton.setBaseSize(QtCore.QSize(13, 14))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.startButton.setFont(font)
        self.startButton.setObjectName("startButton")
        self.horizontalLayout.addWidget(self.startButton)
        self.closeButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closeButton.sizePolicy().hasHeightForWidth())
        self.closeButton.setSizePolicy(sizePolicy)
        self.closeButton.setMinimumSize(QtCore.QSize(120, 30))
        self.closeButton.setBaseSize(QtCore.QSize(13, 14))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.closeButton.setFont(font)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout.addWidget(self.closeButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1050, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.startButton.clicked.connect(self.click)
        self.closeButton.clicked.connect(self.click_exit);
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Linear Regression"))
        self.groupBox.setTitle(_translate("MainWindow", "Dane"))
        self.maxValidate.setText(_translate("MainWindow", "Max: 0"))
        self.label_5.setText(_translate("MainWindow", "Ilość przykładów walidacyjnych"))
        self.label_3.setText(_translate("MainWindow", "Ilość przykładów terningowych"))
        self.label.setText(_translate("MainWindow", "Zbiór treningowy - obrazy"))
        self.maxTraining.setText(_translate("MainWindow", "Max :0"))
        self.label_2.setText(_translate("MainWindow", "Zbiór walidacyjny - obrazy"))
        self.label_11.setText(_translate("MainWindow", "Zbiór treningowy - etykiety"))
        self.label_12.setText(_translate("MainWindow", "Zbiór walidacyjny - etykiety"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Hiperparametry"))
        self.label_10.setText(_translate("MainWindow", "Momentum"))
        self.label_9.setText(_translate("MainWindow", "Liczba epoch"))
        self.label_8.setText(_translate("MainWindow", "Współczynnik l2"))
        self.label_7.setText(_translate("MainWindow", "Długość kroku"))
        self.testowy_label1.setText(_translate("MainWindow", "aaaaaaaaaaaaaaaaaaaaa"))
        self.testowy_label2.setText(_translate("MainWindow", "bbbbbbbbbbbbbbb"))
        self.testowy_label3.setText(_translate("MainWindow", "ccccccccc"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.closeButton.setText(_translate("MainWindow", "Zamknij"))

    def click(self):
        _translate = QtCore.QCoreApplication.translate
        new = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        new.setObjectName("new")
        self.verticalLayout_3.addWidget(new)
        new.setText(_translate("MainWindow", "nowy label"))

    def click_exit(self):
        exit();



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
